eligibility checker
SFDigitalServices/vaccination-distribution pull request #18
Opened 2021-01-17 22:08 UTC by henryjiang-sfgov

Runs a cron job or trigger manually to check eligibility and sends out an eligibility email to everyone in current tier.

How to run it locally:
curl -X GET -H 'ACCESS_KEY: 123456'  -H " application/json"  'http://127.0.0.1:8000/elgibility-checker?phase=phase1b'

2021-01-17 23:42 UTC, josh-chou requested changes

2021-01-17 23:42 UTC, josh-chou commented on service/resources/eligibility_checker.py
> +        timezone = pytz.timezone('America/Los_Angeles')
can't we use LOCAL_TZ here?
or delete LOCAL_TZ if it's not being used anywhere.

2021-01-17 23:42 UTC, josh-chou commented on service/resources/eligibility_checker.py
> +        status = NotificationService().send_notifications('eligiblilty', submission)
spelling.  eligibility.
This string should get replaced with NotificationTypes.ELIGIBILITY after https://github.com/SFDigitalServices/vaccination-distribution/pull/19 is approved and merged.

2021-01-17 23:42 UTC, josh-chou commented on service/microservice.py
> +    api.add_route('/elgibility-checker', EligibilityChecker())
spelling. eligibility-checker.

2021-01-18 00:46 UTC, henryjiang-sfgov commented on service/resources/eligibility_checker.py
> +        status = NotificationService().send_notifications('eligiblilty', submission)
yes I caught that.

2021-01-18 04:02 UTC, josh-chou approved these changes

2021-01-18 05:56 UTC, cschlessinger commented on service/resources/eligibility_checker.py
> +                _records = get_eligible_list(self.session, phase) # querys the db for all individuals without phase assignment
```suggestion
                _records = get_eligible_list(self.session, phase) # queries the DB for all individuals with the given phase assignment
```

2021-01-18 05:56 UTC, cschlessinger commented on service/resources/eligibility_checker.py
> +        # send confirmation email, updates confirmation_sent
This says confirmation email and confirmation_sent but it's passing an eligibility notification - if the comment is wrong, can you update it? Or if it is sending confirmation emails, what am I missing?

2021-01-18 18:41 UTC, henryjiang-sfgov commented on service/resources/eligibility_checker.py
> +        # send confirmation email, updates confirmation_sent
updated comment

2021-01-18 18:41 UTC, henryjiang-sfgov commented on service/resources/eligibility_checker.py
> +                _records = get_eligible_list(self.session, phase) # querys the db for all individuals without phase assignment
updated comment

2021-01-18 18:41 UTC, merged