Phase calculation
SFDigitalServices/vaccination-distribution pull request #8
Opened 2021-01-16 21:48 UTC by hshaosf

Phase calculation and tests

also created `/phase` endpoint so we can test the calculator directly. Sample JSON mock can /tests/mocks/submission_data.json 

```
curl --location --request POST 'https://<host>/phase' \
--header 'ACCESS_KEY: 123456' \
--header 'Content-Type: application/json' \
--data-raw '{...}'
```

2021-01-16 22:39 UTC, cschlessinger requested changes

2021-01-16 22:39 UTC, cschlessinger commented on .env.example
>  CURRENT_PHASE=1A
Since we need to track tiers as well, I'd recommend renaming this to be structured like:
CURRENT_PHASE_AND_TIER=1A
ACTIVE_PHASES=1A

(we can't have 1B and beyond in the active phases for launch)
I think the structure for those phases we be like 1B-1 for Phase 1B Tier 1, 1B-2 for Phase 1B Tier 2, etc.

For future people, let's assign them to like 9 just in case we do move to 2 and need to reclassify them, then we don't have people in a placeholder phase that could soon become real

2021-01-16 22:39 UTC, cschlessinger commented on service/models/phase_calc.py
> +        risk_condition = data["couldYouBeAtRiskFromCovid19BecauseOfAHealthCondition"]
New form questions that will be a factor here:


- Do you work in person/virtually
- Do you live in a congregate setting
- Do you live in a nursing home, assisted living, or a residential care facility?

2021-01-17 18:46 UTC, cschlessinger commented on service/models/phase_calc.py
> +        current = os.getenv('CURRENT_PHASE_AND_TIER')
The current phase should be included in `ACTIVE_PHASES` so we don't need to check for this separately

2021-01-17 18:46 UTC, cschlessinger commented on service/models/phase_calc.py
> +        phases = PhaseCalc.get_phases()
```suggestion
        all_active_phases = PhaseCalc.get_phases()
```

2021-01-17 18:46 UTC, cschlessinger commented on service/models/phase_calc.py
> +    def get_phases():
```suggestion
    def get_all_active_phases():
```

2021-01-17 18:46 UTC, cschlessinger commented on service/models/phase_calc.py
> +    def get_phase(data):
```suggestion
    def get_phase_assignment(data):
```

2021-01-17 18:46 UTC, cschlessinger commented on service/models/phase_calc.py
> +        if job == "healthCareOrPublicHealth":
Forgot to say that this should also have a check for people not working remotely

2021-01-17 18:46 UTC, cschlessinger commented on service/models/phase_calc.py
> +    def get_last_phase():
I'm confused about what this method is doing - is this meant to be for people who don't have a phase/are in future phases?

2021-01-17 18:50 UTC, cschlessinger commented
Made a few renaming suggestions just to be a bit more clear and one calculation logic change but otherwise logic looks kosher to me but def should have an engineer sign off on the code!

2021-01-17 19:15 UTC, hshaosf commented on service/models/phase_calc.py
> +    def get_last_phase():
This is meant to be the default state when no matches found.

2021-01-17 19:17 UTC, hshaosf commented on service/models/phase_calc.py
> +        current = os.getenv('CURRENT_PHASE_AND_TIER')
@cschlessinger tell me more?

2021-01-17 19:19 UTC, hshaosf commented on service/models/phase_calc.py
> +    def get_last_phase():
open to ideas for better naming tho.  originally I was thinking if we cannot match, we just put them at the last phase, but obviously, the logic changed a little bit.

2021-01-17 19:27 UTC, hshaosf commented on service/models/phase_calc.py
> +        if job == "healthCareOrPublicHealth":
https://github.com/SFDigitalServices/vaccination-distribution/blob/1815fafb5afda438da248c096053f26bbfd62698/service/models/phase_calc.py#L44

2021-01-17 21:11 UTC, cschlessinger commented on service/models/phase_calc.py
> +        current = os.getenv('CURRENT_PHASE_AND_TIER')
If the current phase is 1B, the active phases list will be 1A and 1B
The reason I think we need to keep track of current phase is for moving the phases, so like when we move into 1C from 1B, we need to get all the people in phase 1C to send them the eligibility notification

2021-01-18 01:22 UTC, cschlessinger commented on .env.example
> +ACTIVE_PHASES=1A,1B-1,1B-2,1C
It doesn't look like `CURRENT_PHASE_AND_TIER` is actually being used, right? Maybe we just maintain an array of all the active phases and as soon as a new phase/tier becomes active, we add it to the array? And then when we do the phase movement and eligibility check, since we're going to run it manually, we just pass in the newly active phases/tiers and pass that to the eligibility service. What do you think?

Also would be good to update the var name to indicate it's also by tier, suggestion below

Also also I updated it to match what is currently active in SF

```
ACTIVE_PHASES_AND_TIERS=1A-1, 1A-2,1B-1-1
```

2021-01-18 01:22 UTC, cschlessinger commented on service/models/phase_calc.py
> +    def get_last_phase():
If no phases are found, let's do what you did in line 101 and just make their phase `"no_phase"`

2021-01-18 01:22 UTC, cschlessinger commented on service/models/phase_calc.py
> +    def is_eligible(phase):
Should this method be moved to the `EligibilityChecker` class?

2021-01-18 01:22 UTC, cschlessinger commented on service/models/phase_calc.py
> +        return PhaseCalc.get_last_phase()
Think it's best to just return `"no_phase"` like you're doing below

2021-01-18 01:22 UTC, cschlessinger commented on service/resources/phase_calculator.py
>          """ updates the database with phase """
Doesn't look like there's anything wired up to actually make the database update with the phase?

2021-01-18 01:22 UTC, cschlessinger commented on service/resources/phase_calculator.py
> +            _records = get_confirmation_list(self.session, phase=phase)
What is this list? Are we not just sending the confirmation on each signup?

2021-01-18 01:41 UTC, cschlessinger commented on service/resources/phase_calculator.py
> +    def send_confirmation(self, phase):
From standup: not needed, handled in notification class

2021-01-18 02:14 UTC, hshaosf commented on service/models/phase_calc.py
> +    def get_last_phase():
sounds good. update at https://github.com/SFDigitalServices/vaccination-distribution/pull/8/commits/15fbb0cbf5b84df18647bd3a0cb8ac1b89a9149a 

the no_phase line 101 is for the notification template, which will get replaced once we have set up constants in the notification class.

2021-01-18 02:21 UTC, hshaosf commented on service/models/phase_calc.py
> +    def is_eligible(phase):
By having here, we can share and re-used this function.  For the `Submission`, we need to determine the person is also eligible so we can send the eligible notification in addition to the confirmation notification.

2021-01-18 02:22 UTC, hshaosf commented on service/models/phase_calc.py
> +        return PhaseCalc.get_last_phase()
updated at https://github.com/SFDigitalServices/vaccination-distribution/commit/15fbb0cbf5b84df18647bd3a0cb8ac1b89a9149a

2021-01-18 02:51 UTC, hshaosf commented on .env.example
> +ACTIVE_PHASES=1A,1B-1,1B-2,1C
Yeah, the `CURRENT_PHASE_AND_TIER ` was originally defined at https://github.com/SFDigitalServices/vaccination-distribution/issues/4  and we haven't used it yet. Removing at a2631e1

The ACTIVE_PHASE renaming at https://github.com/SFDigitalServices/vaccination-distribution/pull/8/commits/543a32df2d68318c18031fdb5bfa3f7fd5242258

2021-01-18 03:00 UTC, hshaosf commented on service/resources/phase_calculator.py
> +            _records = get_confirmation_list(self.session, phase=phase)
Yeah, doesn't seem like we need this. It was an artifact from https://github.com/SFDigitalServices/vaccination-distribution/issues/10

2021-01-18 03:02 UTC, hshaosf commented on service/resources/phase_calculator.py
>          """ updates the database with phase """
Correct. We will need to work on it to wire it up.

2021-01-18 03:12 UTC, cschlessinger commented on service/models/phase_calc.py
> +        return PhaseCalc.get_last_phase()
Can't we just return this directly without the method since all the method is doing is returning that string?

2021-01-18 03:22 UTC, hshaosf commented on service/models/phase_calc.py
> +        return PhaseCalc.get_last_phase()
Yup, that can also work. Updated 40d9a68

2021-01-18 05:33 UTC, cschlessinger commented on service/models/phase_calc.py
> +            return "1B-1-2"
This is just "1B-2"

2021-01-18 05:55 UTC, hshaosf commented on service/models/phase_calc.py
> +            return "1B-1-2"
Thanks for catching that. 0acdc35

2021-01-18 06:00 UTC, cschlessinger commented on service/resources/submission.py
> +                NotificationTypes.ELIGIBILITY, submission, subtype_template)
Just to clarify, I'm seeing send_notifications being called with the eligibility argument [here](https://github.com/SFDigitalServices/vaccination-distribution/pull/18/files#diff-4e2ae2ca9a7c695ca6a764a66919e6361412b5119c9a49209ff18d9d58851d63R45) - can you confirm the one in this PR is to check for eligibility when someone signs up, and the one in the Eligibility Checker runs when we move phases?

2021-01-18 06:15 UTC, hshaosf commented on service/resources/submission.py
> +                NotificationTypes.ELIGIBILITY, submission, subtype_template)
@cschlessinger Yeah, I think that's what was discussed during our standup and subsequent slack today.  Might be a good idea to huddle to make sure we are on the same page if there are other understandings.   

The PR started with just calculating Phase, then now morph to also include submission as well for signups.

2021-01-18 06:22 UTC, cschlessinger commented
General question: Does this code handle the case of healthcare workers, whose confirmation email also counts as an eligibility email (i.e. should update the eligibility notification column timestamp at the same time as it sends the confirmation email and updates that column's timestamp)?

2021-01-18 06:28 UTC, hshaosf commented
@cschlessinger 

the healthcare logic is at https://github.com/SFDigitalServices/vaccination-distribution/blob/433c46867f51b5c71f2e8c425f09e4fec159f515/service/resources/submission.py#L63-L69

2021-01-18 06:35 UTC, josh-chou requested changes

2021-01-18 06:35 UTC, josh-chou commented on service/resources/models.py
> +        result_dict = db_session.query(SubmissionModel).filter_by(phase).all()
Does this query work?  You don't need to pass the column to match on?
.filter_by(phase==phase) or .filter_by(SubmissionModel.phase == phase)

2021-01-18 06:35 UTC, josh-chou commented on tests/test_phase_calc.py
> +    assert PhaseCalc.get_phase_template("1B-2") == "no_phase"
Unit tests!!!  🥇

2021-01-18 06:45 UTC, hshaosf commented on tests/test_phase_calc.py
> +    assert PhaseCalc.get_phase_template("1B-2") == "no_phase"
ha. totally forgot to update the tests. 3f173d5

2021-01-18 06:47 UTC, hshaosf commented on service/resources/models.py
> +        result_dict = db_session.query(SubmissionModel).filter_by(phase).all()
That's a typo. Good catch. 8ed80a7

2021-01-18 07:07 UTC, josh-chou approved these changes
engineering approval 🥇

2021-01-18 07:15 UTC, hshaosf commented
@cschlessinger I think this still needs your review and approval before this can be merged.

2021-01-18 18:09 UTC, cschlessinger approved these changes
🎉

2021-01-18 18:11 UTC, merged